exception Syntax_Error of string
exception Not_Supported of string
exception NotKappa_Poset of string
exception Malformed_Decl of string
exception Malformed_Args of string
exception Internal_Error of string
exception Uninterpreted_Variable of string
exception Uninterpreted_Predicate of string
exception Uninterpreted_Function of string
exception Mappings of unit
